karspexet/economy/urls.py
from django.urls import path

from karspexet.economy import views

urlpatterns = [
    path("", views.overview, name="economy_overview"),
    path("<int:show_id>/", views.show_detail, name="economy_show_detail"),
    path("discounts/", views.discounts, name="economy_discounts"),
    path("vouchers/", views.vouchers, name="economy_vouchers"),
]

karspexet/ticket/urls.py
from django.urls import path

from karspexet.ticket import views

urlpatterns = [
    path("", views.home, name="ticket_home"),
    path(
        "reservation/<reservation_code>/",
        views.reservation_detail,
        name="reservation_detail",
    ),
    path(
        "reservation/<reservation_code>/send_reservation_email/",
        views.send_reservation_email,
        name="send_reservation_email",
    ),
    path(
        "reservation/<reservation_id>/apply_voucher",
        views.apply_voucher,
        name="apply_voucher",
    ),
    path(
        "reservation/<reservation_id>/process_payment",
        views.process_payment,
        name="process_payment",
    ),
    path("show/<show_id>/", views.show_redirect, name="show_redirect"),
    path(
        "show/<show_id>/booking_overview/",
        views.booking_overview,
        name="booking_overview",
    ),
    path("show/<show_id>/cancel/", views.cancel_reservation, name="cancel_reservation"),
    path("show/<show_id>/select_seats/", views.select_seats, name="select_seats"),
    path("stripe-webhooks/", views.stripe_webhooks),
    path(
        "ticket/<reservation_id>-<ticket_code>.pdf", views.ticket_pdf, name="ticket_pdf"
    ),
    path(
        "ticket/<reservation_id>-<ticket_code>/",
        views.ticket_detail,
        name="ticket_detail",
    ),
]

karspexet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

urlpatterns = [
    path("500/", TemplateView.as_view(template_name="500.html")),
    path("admin/", admin.site.urls),
    path("economy/", include("karspexet.economy.urls")),
    path("venue/", include("karspexet.venue.urls")),
    path("ticket/", include("karspexet.ticket.urls")),
    re_path(
        r"^favicon\.ico$",
        RedirectView.as_view(url="/static/favicon.ico", permanent=True),
    ),
    # Important to keep this last
    path("", include("cms.urls")),
]

urlpatterns = (
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
        show_indexes=settings.DEBUG,
    )
    + urlpatterns
)
urlpatterns = (
    static(
        settings.MEDIA_THUMBS_URL,
        document_root=settings.MEDIA_THUMBS_ROOT,
        show_indexes=settings.DEBUG,
    )
    + urlpatterns
)
urlpatterns = (
    static(
        settings.MEDIA_FILER_URL,
        document_root=settings.MEDIA_FILER_ROOT,
        show_indexes=settings.DEBUG,
    )
    + urlpatterns
)

karspexet/venue/urls.py
from django.urls import path

from karspexet.venue import views

urlpatterns = [
    path("<venue_id>/seats/", views.manage_seats, name="manage_seats"),
]

karspexet/ticket/models.py
from __future__ import annotations

import enum
from datetime import date
from string import ascii_uppercase, digits

from django.conf import settings
from django.contrib.postgres.fields import HStoreField
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string

from karspexet.venue.models import Seat


class TicketType(str, enum.Enum):
    normal = "normal"
    student = "student"
    sponsor = "sponsor"

    def __str__(self) -> str:
        return self.value


TICKET_TYPES = [
    (TicketType.normal, "Fullpris"),
    (TicketType.student, "Student"),
    (TicketType.sponsor, "Sponsor"),
]


def _generate_random_code(length=12):
    return get_random_string(length=length, allowed_chars=ascii_uppercase + digits)


def _generate_voucher_code():
    return _generate_random_code(length=16)


def _next_fifteenth_september():
    # By the 15nth of September, the previous show season is usually over
    today = timezone.now().date()
    fifteenth_september_this_year = date(today.year, 9, 15)
    fifteenth_september_next_year = date(today.year + 1, 9, 15)

    if today >= fifteenth_september_this_year:
        return fifteenth_september_next_year
    else:
        return fifteenth_september_this_year


class ActiveReservationsManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(Q(session_timeout__gt=timezone.now()) | Q(finalized=True))
        )


class Reservation(models.Model):
    show = models.ForeignKey("show.Show", null=False, on_delete=models.CASCADE)
    ticket_price = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    tickets = HStoreField()
    session_timeout = models.DateTimeField()
    finalized = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    reservation_code = models.CharField(
        unique=True, max_length=16, default=_generate_random_code
    )

    objects = models.Manager()
    active = ActiveReservationsManager()

    def __repr__(self):
        fields = ["id", "show_id"]
        fields_str = (", ".join(f"{f}={getattr(self, f)}" for f in fields),)
        return f"<{type(self).__name__}({fields_str})"

    def __str__(self):
        return repr(self)

    def save(self, *args, **kwargs) -> None:
        self.calculate_ticket_price_and_total()
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse(
            "reservation_detail", kwargs={"reservation_code": self.reservation_code}
        )

    def get_amount(self) -> int:
        return self.total * 100  # Price in Öre

    def is_free(self) -> bool:
        return self.get_amount() == 0

    def seat_ids(self) -> list:
        if not self.tickets:
            return []
        return list(self.tickets.keys())

    def seats(self):
        return Seat.objects.filter(pk__in=self.seat_ids()).all()

    def ticket_set(self):
        return Ticket.objects.filter(show=self.show).filter(seat_id__in=self.seat_ids())

    def num_tickets(self) -> int:
        return len(self.seat_ids())

    def apply_voucher(self, code) -> Discount:
        if Discount.objects.filter(reservation=self).exists():
            raise AlreadyDiscountedException(
                "This reservation already has a discount: reservation_id=%d existing_discount_code=%s new_code=%s"
                % (self.id, self.discount.voucher.code, code)
            )
        if Discount.objects.filter(Q(voucher__code=code)).exists():
            raise InvalidVoucherException(
                "Voucher has already been used: code=%s" % code
            )
        voucher = Voucher.objects.get(code=code)
        amount = min(self.ticket_price, voucher.amount)
        discount = Discount.objects.create(
            reservation=self, voucher=voucher, amount=amount
        )
        self.total = self.ticket_price - amount

        return discount

    def calculate_ticket_price_and_total(self) -> None:
        self.ticket_price = sum(
            int(seat.price_for_type(self.tickets[str(seat.id)]))
            for seat in self.seats()
        )
        try:
            self.total = self.ticket_price - self.discount.amount
        except ObjectDoesNotExist:
            self.total = self.ticket_price

    def build_tickets(self, seats: dict[str, list[Seat]]) -> None:
        tickets = {}
        for price, price_seats in seats.items():
            for seat in price_seats:
                tickets[str(seat.id)] = price

        if len(tickets) != sum(map(len, seats.values())):
            raise MultipleTicketTypeException(
                "One seat may not have multiple ticket types"
            )

        self.tickets = tickets


class Account(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} <{self.email}>"


class Ticket(models.Model):
    price = models.PositiveIntegerField()
    ticket_type = models.CharField(
        max_length=10, choices=TICKET_TYPES, default="normal"
    )
    show = models.ForeignKey("show.Show", null=False, on_delete=models.PROTECT)
    seat = models.ForeignKey("venue.Seat", null=False, on_delete=models.PROTECT)
    account = models.ForeignKey(Account, null=False, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    ticket_code = models.CharField(
        unique=True, max_length=16, default=_generate_random_code
    )
    reference = models.CharField(max_length=255, null=False, blank=True, default="")

    class Meta:
        unique_together = ("show", "seat")

    def __repr__(self):
        return f"<Ticket {self.ticket_type} | {self.show} | {self.seat}>"

    def __str__(self):
        if self.show.free_seating:
            return str(self.seat.group)
        else:
            return f"{self.show}, {self.seat.group}, {self.seat}"

    def get_reservation(self) -> Reservation | None:
        qs = Reservation.objects.filter(show=self.show, finalized=True)
        return qs.filter(tickets__keys__overlap=[self.seat_id]).first()


class VoucherQuerySet(models.QuerySet):
    def active(self):
        return self.exclude(id__in=Discount.objects.values_list("id", flat=True))


class Voucher(models.Model):
    """
    A voucher valid for getting a discount on one single Reservation.

    Vouchers cannot be partially applied to a Reservation, so any excess value is void after use.
    """

    amount = models.PositiveIntegerField(help_text="Rabatt i SEK")
    code = models.CharField(
        unique=True, max_length=16, null=False, default=_generate_voucher_code
    )
    expiry_date = models.DateField(null=False, default=_next_fifteenth_september)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)
    note = models.CharField(max_length=255, null=False, default="")

    objects = VoucherQuerySet.as_manager()

    @staticmethod
    def active():
        return Voucher.objects.exclude(
            id__in=Discount.objects.values_list("id", flat=True)
        )

    def __str__(self):
        return f"id={self.id} amount={self.amount} code={self.code}"


class Discount(models.Model):
    """
    A model representing a given discount on a specific reservation.

    This is a connecting model between a Voucher and a Reservation.

    A Voucher can only ever be discounted to one single Reservation, and a
    Reservation can only ever have one single Discount applied.
    """

    amount = models.PositiveIntegerField(
        validators=[MinValueValidator(100), MaxValueValidator(5000)], null=False
    )
    reservation = models.OneToOneField(
        Reservation, null=False, unique=True, on_delete=models.CASCADE
    )
    voucher = models.OneToOneField(
        Voucher, null=False, unique=True, on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)

    def unused_amount(self) -> int:
        return self.voucher.amount - self.amount


class ActivePricingModelManager(models.Manager):
    def active(self, timestamp=None):
        if not timestamp:
            timestamp = timezone.now()
        return (
            super()
            .get_queryset()
            .filter(valid_from__lte=timestamp)
            .order_by("-valid_from")
        )


class PricingModel(models.Model):
    """
    A pricing model for a seating group.
    """

    seating_group = models.ForeignKey(
        "venue.SeatingGroup", null=False, on_delete=models.PROTECT
    )
    prices = HStoreField(null=False)
    valid_from = models.DateTimeField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified_at = models.DateTimeField(auto_now=True)

    objects = ActivePricingModelManager()

    def __repr__(self):
        return (
            "<PricingModel(id={}, prices={}, seating_group={}, valid_from={})>".format(
                self.id, self.prices, self.seating_group, self.valid_from
            )
        )

    def __str__(self):
        return f"PricingModel {self.id} {self.valid_from} {self.prices} {self.seating_group}"

    def price_for(self, ticket_type) -> int:
        return int(self.prices[ticket_type])

    def save(self, **kwargs):
        if not self.prices:
            self.prices = {}

karspexet/economy/forms.py
from django import forms

from karspexet.ticket.models import Voucher


class VoucherForm(forms.ModelForm):
    amount = forms.IntegerField(
        required=True,
        label="Belopp",
        min_value=1,
    )
    note = forms.CharField(
        required=True,
        label="Beskrivning",
        max_length=255,
        help_text="Tex. vem som ska få rabatten",
    )

    def __init__(self, created_by, **kwargs):
        super().__init__(**kwargs)
        self.instance.created_by = created_by

    class Meta:
        model = Voucher
        fields = ["amount", "note"]

karspexet/economy/views.py
from collections import defaultdict

from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse

from karspexet.economy.forms import VoucherForm
from karspexet.show.models import Show
from karspexet.ticket.models import Discount, Ticket, Voucher


@staff_member_required
def overview(request):
    shows = Show.objects.order_by("-date").annotate_ticket_coverage()
    return TemplateResponse(
        request,
        "economy/overview.html",
        context={
            "shows": shows,
            "user": request.user,
        },
    )


@staff_member_required
def show_detail(request, show_id):
    shows = Show.objects.filter(id=show_id).annotate_ticket_coverage()
    show = shows[0]

    tickets = show.ticket_set.select_related("seat", "account")
    taken_seats = Ticket.objects.filter(show=show).values_list("seat_id", flat=True)
    ticket_counts: dict[str, int] = defaultdict(int)
    for t in tickets:
        ticket_counts[t.ticket_type] += 1

    return TemplateResponse(
        request,
        "economy/show_detail.html",
        context={
            "show": show,
            "taken_seats": taken_seats,
            "tickets": tickets,
            "ticket_counts": ticket_counts,
            "user": request.user,
        },
    )


@staff_member_required
def discounts(request):
    discounts = Discount.objects.select_related("reservation", "voucher").all()

    return TemplateResponse(
        request,
        "economy/discounts.html",
        context={
            "discounts": discounts,
        },
    )


@staff_member_required
def vouchers(request):
    vouchers = Voucher.objects.active().order_by("-created_at")

    form = VoucherForm(data=request.POST or None, created_by=request.user)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect("economy_vouchers")

    return TemplateResponse(
        request,
        "economy/vouchers.html",
        context={
            "form": form,
            "vouchers": vouchers,
        },
    )

karspexet/venue/views.py
from __future__ import annotations

import logging

from django import forms
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Count
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from karspexet.venue.models import Seat, SeatingGroup, Venue

logger = logging.getLogger(__name__)


class AddSeatsForm(forms.Form):
    num_seats = forms.IntegerField(min_value=1)
    group = forms.IntegerField(widget=forms.HiddenInput)


@staff_member_required
def manage_seats(request: HttpRequest, venue_id: int) -> HttpResponse:
    """
    Backoffice view to easily add Seats to a Venue
    """
    venue: Venue = Venue.objects.filter(id=venue_id).first()
    if not venue:
        raise Http404

    group_qs = SeatingGroup.objects.filter(venue=venue).annotate(
        num_seats=Count("seat")
    )
    groups: list[SeatingGroup] = list(group_qs)

    if request.method == "POST":
        form = AddSeatsForm(data=request.POST)
        form.is_valid()
        if form.is_valid():
            group = form.cleaned_data["group"]
            num_seats = form.cleaned_data["num_seats"]
            for i in range(num_seats):
                number = Seat.objects.filter(group__venue=venue).count() + 1
                seat = Seat.objects.create(
                    group_id=group,
                    name="Plats %s" % number,
                    x_pos=0,
                    y_pos=0,
                )
                logger.info("Created %s - %s", venue.name, seat.name)
            messages.success(request, f"Skapade {num_seats} extra sittplatser")
        return redirect("manage_seats", venue_id=venue.id)

    return render(
        request,
        "venue/manage_seats.html",
        {
            "venue": venue,
            "groups": groups,
        },
    )

karspexet/templates/_footer.html
{% load static %}
<footer class="max-w-screen-lg mx-auto footer">
  <div class="max-w-screen-lg w-full mx-auto flex items-center justify-between">
    <div class="relatedLinks">
      <a href="http://ths.kth.se/"><img class="thsLogo" src="{% static 'ths_logo.png' %}" alt="THS Logotyp"/></a>
    </div>
    <span class="secondary-menu flex items-center h-full ml-4 mr-auto">
      <a href="/foretag">Företag</a>
      <a href="/kontakt">Kontakt</a>
    </span>
    <div class="socialMedia">
      <span class="flex items-center">
        <span class="mr-1">
          Följ oss!
        </span>
        <a href="https://www.facebook.com/karspexet.kth/" class="text-gold inline-flex h-8 w-8 ml-4 mr-4">
          {% include "icons/facebook-square.svg" %}
          <span class="sr-only">Facebook</span>
        </a>
        <a href="https://www.instagram.com/karspexet/" class="text-gold inline-flex h-8 w-8">
          {% include "icons/instagram.svg" %}
          <span class="sr-only">Instagram</span>
        </a>
      </span>
    </div>
  </div>
</footer>

karspexet/templates/about.html
{% extends "base.html" %}
{% load cms_tags %}
{% block content %}
  <div class="content_container">
    <h1>{% placeholder "title" %}</h1>
    <p>{% placeholder "content" %}</p>
  </div>
{% endblock %}

karspexet/templates/base.html
{% load menu_tags cms_tags sekizai_tags static svg %}
<!doctype html>
<html lang="sv">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% page_attribute "page_title" %}{% endblock %}</title>
    <meta name="description" content="{% page_attribute 'meta_description' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    {% render_block "css" %}
  </head>
  <body>
    {% cms_toolbar %}
    <div class="max-w-screen-lg w-full mx-auto">
      <header class="navbar">
        <img class="luva luva-mobile" src="{% static 'svg/luva.svg' %}" alt="">
        <input type="checkbox" class="nav-toggle" id="nav-toggle" />
        <label for="nav-toggle" class="nav-toggle-label">
          <span></span>
        </label>
        <nav class="nav">
          <ul>
            {% show_menu 0 100 100 0 "menu.html" %}
          </ul>
        </nav>
      </header>
      <main>
        {% block content %}
        {% endblock content %}
      </main>
    </div>

    {% include "_footer.html" %}

    {% block main_js %}{% endblock %}
    {% render_block "js" %}
    {% render_block "tracking" %}
  </body>
</html>
{% addtoblock "js" %}<script src="https://js.stripe.com/v3/"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script type="module" src="{% static 'js/index.js' %}"></script>{% endaddtoblock %}
{% addtoblock "css" %}<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">{% endaddtoblock %}
{% addtoblock "css" strip %}
  <style type="text/css" media="screen">
    {% include "_fonts.css" %}
  </style>
{% endaddtoblock %}
{% addtoblock "tracking" %}
<!-- Facebook Pixel Code -->
<script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js'); fbq('init', '1024309724883959');fbq('track', 'PageView');</script>
<noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=1024309724883959&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Pixel Code -->
{% endaddtoblock %}

karspexet/templates/base_backstage.html
{% extends "base.html" %}
{% load static sekizai_tags %}
{% block main_js %}
  {{ block.super }}
  {% addtoblock "js" %}<script type="text/javascript" src="{% static 'js/backstage.js' %}"></script>{% endaddtoblock %}
{% endblock %}

karspexet/templates/content_with_hero_image.html
{% extends "base.html" %}
{% load cms_tags %}
{% block content %}
  <div class="poster_container">
    <div class="poster_image">
      {% placeholder "hero_image" %}
      <div class="poster_title">
        <h1>{% placeholder "Show Title" %}</h1>
        <p>{% placeholder "eller-titel" %}</p>
      </div>
    </div>
  </div>
  <div class="content_container px-4">
    <h1>{% placeholder "title" %}</h1>
    <p>{% placeholder "content" %}</p>
  </div>
{% endblock %}

karspexet/templates/home.html
{% extends "base.html" %}
{% load cms_tags %}
{% block content %}
  <div class="poster_container">
    <div class="poster_image">
      {% placeholder "hero_image" %}
      <div class="poster_title">
        <h1>{% placeholder "Show Title" %}</h1>
        <p>{% placeholder "eller-titel" %}</p>
      </div>
    </div>
  </div>
  <div class="card_container">
    <div class="card">
      <div class="card_image">{% placeholder "card_1_image" %}</div>
      <div class="card_title"> {% placeholder "card 1 Title" %}</div>
      <div class="card_text"> {% placeholder "card 1 text" %}</div>
      <div class="card_link"> {% placeholder "card 1 link" %} </div>
    </div>
    <div class="card">
      <div class="card_image">{% placeholder "card_2_image" %}</div>
      <div class="card_title"> {% placeholder "card 2 Title" %}</div>
      <div class="card_text"> {% placeholder "card 2 text" %}</div>
      <div class="card_link"> {% placeholder "card 2 link" %} </div>
    </div>
    <div class="card">
      <div class="card_image">{% placeholder "card_3_image" %}</div>
      <div class="card_title"> {% placeholder "card 3 Title" %}</div>
      <div class="card_text"> {% placeholder "card 3 text" %}</div>
      <div class="card_link"> {% placeholder "card 3 link" %} </div>
    </div>
  </div>
  <div class="partnersContainer">
    <h2 class="ourPartners">Våra samarbetspartner</h2>
    <div class="partnerPictures">
      {% placeholder "sponsor_images" %}
    </div>
  </div>
{% endblock %}

karspexet/templates/menu.html
{% load static %}
{% for child in children %}
  <li class="child{% if child.selected %} selected{% endif %}{% if child.ancestor %} ancestor{% endif %}{% if child.sibling %} sibling{% endif %}{% if child.descendant %} descendant{% endif %}">
    <a class="nav-link"href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
  </li>
  {% if not forloop.last %}
    {% if forloop.counter == forloop.revcounter|add:"-1" %}
      <li>
        <a href="/">
          <img class="luva luva-mobile" src="{% static 'svg/luva.svg' %}" alt="">
        </a>
      </li>
    {% else %}
      <li class="list-decorator">
        <span class="text-gold flex h-2">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8z" /></svg>
        </span>
      </li>
    {% endif %}
  {% endif %}
{% endfor %}

karspexet/templates/reservation_detail.html
{% extends "ticket/base.html" %}
{% load static svg %}
{% block ticket_content %}
  <div class="content_container ticket-detail max-w-prose">
    <div class="ticket-detail-header">
      <p>Välkommen till Kårspexet</p>
      <h1>{{ production.name }}</h1>
      <p class="alt-name">{{ production.alt_name }}</p>
      <ul class="show-info">
        <li class="mb-1">
          <span class="inline-flex items-center mr-2">
            <span class="inline-flex text-gold items-center justify-center mr-1">
              {% include "icons/calendar.svg" %}
            </span>
            <em class="leading-none">{{ show.date|date:"Y-m-d" }}</em>
          </span>

          <span class="inline-flex items-center">
            <span class="inline-flex text-gold items-center justify-center mr-1">
              {% include "icons/clock.svg" %}
            </span>
            <em class="leading-none">{{ show.date|date:"H:i" }}</em>
          </span>
        </li>
      </li>
      <li class="inline-flex items-center">
        <span class="inline-flex text-gold items-center justify-center mr-1">
          {% include "icons/map-pin.svg" %}
        </span>
        <address class="leading-none"><em>{{ venue.name }}, {{ venue.address }}</em></address>
      </li>
      {% if venue.map_address %}
        <li><a href="{{ venue.map_address }}" target="_blank">Öppna på karta</a></li>
      {% endif %}
    </ul>
  </div>
  {% if messages %}
    <section>
      <ul class="messages">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
  <main class="pb-4 max-w-prose reservation-details">
    <h2>Här finner du dina biljetter</h2>

    <ul>
      {% for ticket in tickets %}
        <li>
          <a href="{% url 'ticket_pdf' reservation.id ticket.ticket_code %}">
            {{ ticket.seat.group.name }} ({{ ticket.get_ticket_type_display }})
          </a>
        </li>
      {% endfor %}
    </ul>

    <p>
      Vi kommer skicka ett mail till dig med den här informationen och en länk till
      den här sidan.
    </p>

    <p class="flex gap-2 bg-red-darker p-4 my-4 rounded">
      <span class="text-gold">{% include "icons/exclamation.svg" %}</span>
      Ibland kommer vissa mail inte fram, så vi rekommenderar att du laddar ner
      biljetterna härifrån på en gång, eller sparar en länk till denna sida.
    </p>

    <form action="{% url 'send_reservation_email' reservation.reservation_code %}" method="post" class="w-56 styled-form">
      {% csrf_token %}
      <div class="mb-2">
        {{ email_form.email }}
      </div>
      <button type="submit">
        Skicka bokningen via E-post
      </button>
    </form>
  </main>
  </div>
{% endblock %}